<a href="https://colab.research.google.com/github/MuntahaTazeem5/Basic-Numpy-Projects/blob/main/image_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Image Processing (Grayscale Filter)**

**Problem Statement:**

A grayscale image is represented as a 2D NumPy array (each value = pixel intensity). You need to:

Increase brightness by +50 (but cap at 255)

Flip the image horizontally

Find the average pixel intensity

👉 Methods you’ll use:

np.clip() (to cap values)

np.fliplr() (flip left-right)

np.mean()

In [1]:
import numpy as np

In [2]:
image=np.array([
    [120,200,90,30,225],
    [60,80,100,200,220],
    [30,40,50,60,70],
    [180,190,200,210,220],
    [10,20,30,40,50]
    ])

In [3]:
bright_image=np.clip(image+50,0,225)


In [4]:
print("\n Brightened Image: \n",bright_image)


 Brightened Image: 
 [[170 225 140  80 225]
 [110 130 150 225 225]
 [ 80  90 100 110 120]
 [225 225 225 225 225]
 [ 60  70  80  90 100]]


In [6]:
flipped_image=np.fliplr(bright_image)

In [7]:
print("\n Horizontally Flipped Image: ",flipped_image)


 Horizontally Flipped Image:  [[225  80 140 225 170]
 [225 225 150 130 110]
 [120 110 100  90  80]
 [225 225 225 225 225]
 [100  90  80  70  60]]


In [8]:
avg_intensity=np.mean(flipped_image)


In [9]:
print("Average Pixel Intensity is: ",avg_intensity)

Average Pixel Intensity is:  148.2
